version: 2.1

jobs:
  test:
    steps:
      - checkout
      - run:
          command: npm test

workflows:
  build:
    jobs:
      - test:
          pre-steps: # steps to run before steps defined in the job bar
            - run:
                command: cp .env.example .env
