version: 2.1
orbs:
  node: circleci/node@3.0.0
workflows:
  node-tests:
    jobs:
      - node/test:
          pre-steps: # steps to run before steps defined in the job bar
            - run:
                command: ls -l cp .env.example .env
